# Generated by Django 4.2.11 on 2024-04-23 21:54

from django.db import migrations, models
import django.db.models.deletion
import urban_performance.up_geo.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpatialFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('BF', 'Base Footprint'), ('BT', 'Base Transit'), ('HZ', 'Hazard'), ('NB', 'NBS'), ('AF', 'Additional Footprints'), ('AT', 'Additional Transit')], max_length=2)),
                ('archivo', models.FileField(upload_to=urban_performance.up_geo.models.spatial_path)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.proyecto')),
            ],
        ),
    ]
