# Generated by Django 4.2.11 on 2024-04-30 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('up_geo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spatialfile',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
