# Generated by Django 4.2.11 on 2024-05-28 14:40

import os, shutil
from django.db import migrations
from urban_performance.up_geo.models import SpatialOpts, spatial_path


def insert_default_spatial_files(apps, schema_editor):
    return


def backwards(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ("up_geo", "0002_spatialfile_descripcion"),
        ("projects", "0009_create_default_projects"),
    ]

    operations = [
        migrations.RunPython(insert_default_spatial_files, backwards),
    ]
