# Generated by Django 4.2.11 on 2024-05-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_indicador_unidad_alter_control_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='escenario',
            name='posicion',
            field=models.IntegerField(default=1),
        ),
    ]
