# Generated by Django 4.2.11 on 2024-05-14 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_escenario_posicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='estatus',
            field=models.CharField(choices=[('PR', 'Processing proyect'), ('RD', 'Ready to use')], default='PR', max_length=2),
        ),
    ]
