# Generated by Django 4.2.11 on 2024-05-15 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_proyecto_estatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='controles',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='estatus',
            field=models.CharField(choices=[('PR', 'Processing proyect'), ('RD', 'Ready to use')], default='RD', max_length=2),
        ),
    ]
