# Generated by Django 4.2.11 on 2024-05-28 15:47

from django.db import migrations, models
import urban_performance.projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_proyecto_controles_alter_proyecto_estatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='controles',
            field=models.FileField(blank=True, null=True, upload_to=urban_performance.projects.models.controls_path),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='estatus',
            field=models.CharField(choices=[('PR', 'Processing proyect'), ('RD', 'Ready to use')], default='PR', max_length=2),
        ),
    ]
