# Generated by Django 4.2.11 on 2024-06-03 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_proyecto_controles_alter_proyecto_estatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyecto',
            old_name='es_publico',
            new_name='uso_como_template',
        ),
    ]
