# Generated by Django 4.2.11 on 2024-06-03 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_rename_es_publico_proyecto_uso_como_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='visibilidad_publica',
            field=models.BooleanField(default=False),
        ),
    ]
