# Generated by Django 4.2.11 on 2024-06-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_create_default_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='estatus',
            field=models.CharField(choices=[('PR', 'Processing proyect'), ('RD', 'Ready to use'), ('ER', 'Error')], default='PR', max_length=2),
        ),
    ]
