# Generated by Django 4.2.11 on 2024-08-23 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_control_active_alter_control_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='niveles',
            field=models.JSONField(default='{{}}'),
        ),
    ]
