# Generated by Django 4.2.11 on 2024-09-14 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_alter_proyecto_niveles'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='partial_processing',
            field=models.JSONField(default=dict),
        ),
    ]
