# Generated by Django 4.2.11 on 2024-05-28 14:35

from django.db import migrations
from django.contrib.auth.hashers import make_password


def insert_default_user(apps, schema_editor):
    User = apps.get_model("users", "User")

    hashed_password = make_password("G@rz@G@rcí@")

    default_User, created = User.objects.get_or_create(
        email="admin@capsus.mx",
        defaults={
            "password": hashed_password,
        },
        is_superuser=True,
        is_staff=True,
    )


def backwards(apps, schema_editor):
    User = apps.get_model("users", "User")

    # Find and delete the user with the specified email.
    user = User.objects.filter(
        email="admin@capsus.mx",
    )
    if user.exists():
        user.first().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(insert_default_user, backwards),
    ]
